config/routes.rb
Rails.application.routes.draw do
  resources :bookrooms
  # resources :mydatabases
  # get 'home/index'
  get 'home/bookroom'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookroom.rb
class Bookroom < ApplicationRecord
end

app/models/mydatabase.rb
class Mydatabase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookrooms_controller.rb
class BookroomsController < ApplicationController
  before_action :set_bookroom, only: %i[ show edit update destroy ]

  def index
    @bookrooms = Bookroom.all
  end

  def show
  end

  # GET /bookrooms/new
  def new
    @bookroom = Bookroom.new
  end

  def edit
  end

  def create
    @bookroom = Bookroom.new(bookroom_params)

    respond_to do |format|
      if @bookroom.save
        format.html { redirect_to bookroom_url(@bookroom), notice: "Your Room is successfully Booked." }
        format.json { render :show, status: :created, location: @bookroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bookroom.update(bookroom_params)
        format.html { redirect_to bookroom_url(@bookroom), notice: "Your Booking is successfully updated." }
        format.json { render :show, status: :ok, location: @bookroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bookroom.destroy

    respond_to do |format|
      format.html { redirect_to bookrooms_url, notice: "Your Room is Canceled." }
      format.json { head :no_content }
    end
  end

  private
    def set_bookroom
      @bookroom = Bookroom.find(params[:id])
    end

    def bookroom_params
      params.require(:bookroom).permit(:first_name, :last_name, :email, :room_type, :no_of_rooms, :start_time, :end_time, :payment_type, :total_payment, :tip)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def bookroom
  end

  
end

app/controllers/mydatabases_controller.rb
class MydatabasesController < ApplicationController
  before_action :set_mydatabase, only: %i[ show edit update destroy ]

  def index
    @mydatabases = Mydatabase.all
  end

  def show
  end

  def new
    @mydatabase = Mydatabase.new
  end

  def edit
  end

  def create
    @mydatabase = Mydatabase.new(mydatabase_params)

    respond_to do |format|
      if @mydatabase.save
        format.html { redirect_to mydatabase_url(@mydatabase), notice: "Mydatabase was successfully created." }
        format.json { render :show, status: :created, location: @mydatabase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mydatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mydatabase.update(mydatabase_params)
        format.html { redirect_to mydatabase_url(@mydatabase), notice: "Mydatabase was successfully updated." }
        format.json { render :show, status: :ok, location: @mydatabase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mydatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mydatabase.destroy

    respond_to do |format|
      format.html { redirect_to mydatabases_url, notice: "Mydatabase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mydatabase
      @mydatabase = Mydatabase.find(params[:id])
    end

    def mydatabase_params
      params.require(:mydatabase).permit(:first_name, :last_name, :email, :room_type, :no_of_rooms, :start_time, :end_time, :payment_type, :total_payment, :tip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mydatabases_helper.rb
module MydatabasesHelper
end

app/views/bookrooms/_bookroom.html.erb
<div id="<%= dom_id bookroom %>">
  <p>
    <strong>First name:</strong>
    <%= bookroom.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= bookroom.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= bookroom.email %>
  </p>

  <p>
    <strong>Room type:</strong>
    <%= bookroom.room_type %>
  </p>

  <p>
    <strong>No of rooms:</strong>
    <%= bookroom.no_of_rooms %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= bookroom.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= bookroom.end_time %>
  </p>

  <p>
    <strong>Payment type:</strong>
    <%= bookroom.payment_type %>
  </p>

  <p>
    <strong>Total payment:</strong>
    <%= bookroom.total_payment %>
  </p>

  <p>
    <strong>Tip:</strong>
    <%= bookroom.tip %>
  </p>

</div>

app/views/bookrooms/_form.html.erb
<%= form_with(model: bookroom) do |form| %>
  <% if bookroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookroom.errors.count, "error") %> prohibited this bookroom from being saved:</h2>

      <ul>
        <% bookroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="container">
      <div class="form-row">
        <div class="form-group col-md-6">
          <%# <%= form.label :first_name, style: "display: block" %>
          <%= form.text_field :first_name, class:"form-control ", placeholder:'First Name' %>
        </div>

        <div class="form-group col-md-6">
          <%# <%= form.label :last_name, style: "display: block" %>
          <%= form.text_field :last_name , class:"form-control ", placeholder:'Last Name'%>
        </div>

      </div>

      <div class="form-row">
        <div class="form-group col-md-12">
          <%# <%= form.label :email, style: "display: block" %> 
          <%= form.text_field :email, class:"form-control", placeholder:'E-mail' %>
        </div>
      </div>

      <div class="form-row " style="margin-top:3px">
        <div class="form-group col-md-6 form-check " style="margin-top: -5px">
          <%= form.label :room_type, "Room Type ", class:"form-check-label" %>

          <div style="display: block; margin-left: 20px ;">
            <%= form.radio_button :room_type, "Luxary",class:"form-check-input" %>
            <%= form.label :room_type, "Luxary" %>
            <%= form.radio_button :room_type, "Semi-Luxary" %>
            <%= form.label :room_type, "Semi-Luxary" %>
            <%= form.radio_button :room_type, "Non-AC" %>
            <%= form.label :room_type, "Non-AC" %>
          </div>

        </div>

        <div class="form-group col-md-6">
          <%# <%= form.label :no_of_rooms, style: "display: block" %> 
          <%= form.number_field :no_of_rooms,class:"form-control",placeholder:"No. Of Rooms" %>
        </div>

        
      </div>


      <div class="form-row" style="margin-top:-7px">

        <div class="form-group col-md-6">
          <%= form.label :start_time, style: "display: block" %>
          <%= form.time_field :start_time %>
        </div>

        <div class="form-group col-md-6">
          <%= form.label :end_time, style: "display: block" %>
          <%= form.time_field :end_time %>
        </div>
        
      </div>


      <div class="form-row" style="margin-top:5px">

        <div class="form-group col-md-6">
          <%= form.label :payment_type, "Payment Type ", class:"form-check-label" %>
          <div style="display: block; margin-left: 20px ;">
            <%= form.radio_button :payment_type, "UPI",class:"form-check-input" %>
            <%= form.label :payment_type, "UPI" %>
            <%= form.radio_button :payment_type, "Cash" %>
            <%= form.label :payment_type, "Cash" %>
            <%= form.radio_button :payment_type, "Card" %>
            <%= form.label :payment_type, "Card" %>
          </div>
        </div>

        <div class="form-group col-md-6">
          <%# <%= form.label :tip, style: "display: block" %> 
          <%= form.number_field :tip, class:"form-control", placeholder:"Tip To Staff" %>
        </div>


      </div>
      
      <div>
        <%# <%= form.label :total_payment, style: "display: block" %>
        <%# <%= form.number_field :total_payment, class:"form-control", placeholder:"Total Bill" %> 
        <%# <% total=0 %>
        <%# <% if checked:(@bookroom.room_type_value=="Luxary") %> 
          <%# total= 1*100; 
        
        <h3>Your Total is: <%= 100  </h3>
        <% end%>
        <%# <%= link_to "Edit Booking", @bookroom.room_type, class: "btn btn-dark btn-sm" %> 
      
        <%# <%= @bookroom.room_type%>
      </div>


      <%# <div>
        <%# <%= form.label :total_payment, style: "display: block" %>
        <%# <%= form.number_field :total_payment, class:"form-control", placeholder:"Total Bill" 
      </div> %>

      

      <div style="margin-top: 20px ">
        <%= form.submit class:"btn btn-dark btn-sm", value:"Generate Bill" %>
      </div>

      <%# <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/> %>
    </div>
  </form>
<% end %>

app/views/bookrooms/edit.html.erb
<br/>
<center><h2>Edit Booking</h2></center>
<hr style="margin-bottom:50px">
<%= render "form", bookroom: @bookroom %>

<br>

<div>
  <%= link_to "Show this bookroom", @bookroom %> |
  <%= link_to "Back to bookrooms", bookrooms_path %>
</div>

app/views/bookrooms/index.html.erb
<p style="color: green"><%= notice %></p>

<div style=" padding : 20px ">
  
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Room Type</th>
      <th>No. of Rooms</th>
      <th>Arival Time </th>
      <th>Departure Time </th>
      <th>Payment Type </th>
      <th>Any Tip</th>
      <th>Total Payment</th>
      
      <%# <th></th> %>
    </tr>
  </thead>

  <tbody >
      <% @bookrooms.each do |bookroom| %>

        <tr>

          <td>
            <%= link_to bookroom.first_name + ' ' + bookroom.last_name, bookroom %>
          </td>
          <td><%= bookroom.email %></td>
          <td><%= bookroom.room_type %></td>
          <td><%= bookroom.no_of_rooms %></td>
          <td><%= bookroom.start_time %></td>
          <td><%= bookroom.end_time %></td>
          <td><%= bookroom.payment_type %></td>
          <td><%= bookroom.tip %></td>
          <%# <td><%= bookroom.total_payment %></td>
          <td>
            <%= link_to 'Show Bill', bookroom, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-dark btn-sm" %>
          </td>
          
      
        </tr>
          
      <% end %>
  </tbody>
</table>

        
</div>

app/views/bookrooms/new.html.erb
<br/>
<center><h1>Book Room</h1>
</center>
<hr style="margin-bottom:50px">

<%= render "form", bookroom: @bookroom %>

<br>

<div>
  <%= link_to "Home", bookrooms_path %>
</div>

app/views/bookrooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <div style=" padding:'20px'; " > %>
<div class="jumbotron" >
  <h1 class="display-5"><%= @bookroom.first_name+' '+@bookroom.last_name %></h1>
  <p class="lead"><%= @bookroom.email %></p>
  <hr class="my-4">

  <table>
    <tr>
      <td>
        <strong>Arrival:</strong>
        <p class="lead"><%= @bookroom.start_time %></p>
      </td>

      <td>&nbsp</td>

      <td>
        <strong>Room Type:</strong>
        <p class="lead"><%= @bookroom.room_type %></p>
      </td>

      <td>&nbsp&nbsp&nbsp&nbsp</td>

      <td>
        <strong>Payment Type:</strong>
        <p class="lead"><%= @bookroom.payment_type %></p>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Departure:</strong>
        <p class="lead"><%= @bookroom.end_time %></p>
      </td>

      <td>&nbsp&nbsp&nbsp&nbsp&nbsp</td>

      <td>
        <strong>No. of Rooms:</strong>
        <p class="lead"><%= @bookroom.no_of_rooms %></p>
      </td>

      <td>&nbsp&nbsp&nbsp</td>

      <td>
        <strong>Any Tip:</strong>
        <p class="lead"><%= @bookroom.tip %></p>
      </td>
    </tr>


    <% roomcost=0 %> 
    <% if @bookroom.room_type=="Luxary" %>
       <% roomcost = (@bookroom.no_of_rooms * 1000) %>
      <% @bookroom.total_payment= roomcost + (@bookroom.tip) %>
    <% end %>

    <% if @bookroom.room_type=="Semi-Luxary" %>
       <% roomcost = (@bookroom.no_of_rooms * 750) %>
      <% @bookroom.total_payment= roomcost + (@bookroom.tip) %>
    <% end %>

    <% if @bookroom.room_type=="Non-AC" %>
       <% roomcost = (@bookroom.no_of_rooms * 500) %>
      <% @bookroom.total_payment= roomcost + (@bookroom.tip) %>
    <% end %>

    <tr>
      <td>
        <strong>Total Payment:</strong>
        <p class="lead"><%= "No. of Room x Cost of 1 Room : Rs-"  %> <%=  roomcost %></p> 
        <p class="lead"><%= "Tip To Hotel Staff           : Rs-"  %> <%=  @bookroom.tip %></p> 
        <p class="lead"><%= "Total     : Rs-   "  %><%=@bookroom.total_payment %></p>
      </td>

    </tr>

    <tr>
      <td>
        <%= link_to "Edit Booking", edit_bookroom_path(@bookroom), class: "btn btn-dark btn-sm" %> 
      </td>

      <td></td>

      <td>
        <%= button_to "Cancel Booking", @bookroom, method: :delete , class: "btn btn-dark btn-sm"%>
      </td>

    </tr>

  </table>


  
  
</div>

<%# </div> %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <%= link_to 'Hotel Management App', root_path ,class:"navbar-brand"  %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to 'Book Room', new_bookroom_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Show Bookings', bookrooms_path, class:"nav-link" %>
      </li>

      

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/bookroom.html.erb
<h1>Book Room</h1>

app/views/home/index.html.erb
<div class="form-row" style=" padding: 90px; gap: 20px">
    <div class="form-group">
        <div class="card" style="width: 18rem;">
        <div class="card-header">
            <strong>Room Type</strong>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Luxary</li>
            <li class="list-group-item">Semi-Luxary</li>
            <li class="list-group-item">Non-AC</li>
        </ul>
        </div>
    </div>

    <div class="form-group">
        <div class="card" style="width: 18rem;">
        <div class="card-header">
            <strong>Price Per Hour</strong>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">1000</li>
            <li class="list-group-item">750</li>
            <li class="list-group-item">500</li>
        </ul>
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Booking</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
      <div>
        <%= yield %> 
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>